### ISSUE TITLE
Dynamic tile creation

### ISSUE THREAD

**Issue by MatthewTurk** [jwass/mplleaflet#17]
We've used leaflet in the past on running servers that dynamically generated tiles from sparse image format files.  It would be really nice if this could be possible with mplleaflet, although I'm not certain it is possible with the IPython architecture.  What this might look like would be defining a function (essentially a URL handler) that received the x and y map tile indices and the level of detail, and returned a PNG.  It may be possible, but I don't know how to attach a URL handler to the IPython notebook.  Is this feasible to do within mplleaflet?

**Comment by jwass** [comment]
Hi @MatthewTurk,

`mplleaflet` isn't really equipped to be a tile server. I think something like [TileStache](https://github.com/TileStache/TileStache) might be more in line with what you're looking to do...? It would be neat to create a TileStache layer that uses matplotlib to plot data and output the tile image as PNG, although there are other ways to achieve the desired styling too.

Let me know if that makes sense or if I'm off the mark.
