### ISSUE TITLE
contourf example doesn't work on my machine

### ISSUE THREAD

**Issue by shoyer** [jwass/mplleaflet#19]
I can't seem to get any contourf plots to work with mplleaflet. Other plot types (e.g., scatter plots) work fine.

The example runs without any errors on my machine, but it generates a map with only the background layer.

Any ideas for how to debug this?

**Comment by jwass** [comment]
Hi @shoyer.
I just pushed a fix for this, which is really in `mplexporter`. Any way you can give it a try when you get a chance?

**Comment by shoyer** [comment]
It works, thanks!

**Comment by jwass** [comment]
Awesome! Thanks for checking. Updated to new version and pushed to PyPI.

**Comment by shoyer** [comment]
Great!

It might be a good idea to also push tags to github? That makes it a little more obvious that you've made a release.
