### ISSUE TITLE
How to use the plotting on mplleaflet Offline? Is it possible to use the map offline?

### ISSUE THREAD

**Issue by Melzonko** [jwass/mplleaflet#36]
How to use the plotting on mplleaflet Offline? Is it possible to use the map offline? @jwass 

Thanks

**Comment by Melzonko** [comment]
By the way; I'm referring to "basic_plot.py: Simple line/point plotting"  @jwass

**Comment by ocefpaf** [comment]
@Melzonko mplleaflet uses Leaflet to create maps. Leaflet maps require a tile server to produce the map. That mean, unless you have a local server, you cannot use them offline.

(You can take a static snapshot though.)

**Comment by Melzonko** [comment]
@ocefpaf  Yes I have a local  server in my company used for test purposes, and I need to download the slippy map on it "Snapshot will not help".. How can I do that if you please?

BR,
Mohamed

**Comment by ocefpaf** [comment]
*Shameless plug on* if you use [folium](https://github.com/python-visualization/folium) you can just pass your local server to the tiles option. *Shameless plug off*

In mplleaflet you can start [here](https://github.com/jwass/mplleaflet/blob/master/mplleaflet/maptiles.py).

**Comment by Melzonko** [comment]
@ocefpaf  Will try it.. Many Thanks

**Comment by jwass** [comment]
@Melzonko Also, check out the documentation for the `tiles` keyword argument: https://github.com/jwass/mplleaflet/blob/master/mplleaflet/_display.py#L37. You can pass a tuple of (URL, attribution string) to get tiles from your local server.

**Comment by ocefpaf** [comment]
> You can pass a tuple of (URL, attribution string)

My bad! I should have notice that!

**Comment by Melzonko** [comment]
@ocefpaf @jwass  Thanks guys .. You're really supportive. 

BR

**Comment by jwass** [comment]
@ocefpaf No worries! Worth mentioning Folium either way :)
