### ISSUE TITLE
Animations?

### ISSUE THREAD

**Issue by GandalfSaxe** [jwass/mplleaflet#43]
Hi,

Is it possible to somehow make animations on OpenStreetMap using mplleaflet?

Any suggestions on how to achieve this, including adding/modifying the code would be helpful :)

**Comment by jwass** [comment]
Hi @GandalfSaxe,
mplleaflet tries to convert any matplotlib plot into a leaflet map. Animations are beyond the scope. You can always modify mplleaflet's output javascript code, but more likely would have to build the map using the output data.
