### ISSUE TITLE
Polygons are distorted

### ISSUE THREAD

**Issue by FrancoisMB** [jwass/mplleaflet#46]
When plotting a regular polygon, it gets distorted on the map. My guess is that it's because the radius is evaluated as degrees, and 1 degree in latitude is not the same distance as 1 degree in longitude (except at latitude = 0 of course) :

```
import mplleaflet
import matplotlib.pyplot as plt
import matplotlib as mpl

fig, ax = plt.subplots()
lon = 2.363561
lat = 48.951918
r = 20
regpol1 = mpl.patches.RegularPolygon((lon, lat), 16, radius=r, color = 'r')
ax.add_patch(regpol1)

mplleaflet.show(fig = ax.figure)
```
![image](https://user-images.githubusercontent.com/15570583/30702951-a6acd86c-9eee-11e7-819c-04fad78c4ad1.png)

Same thing with lat = 0 => no distortion : 

![image](https://user-images.githubusercontent.com/15570583/30703249-70b91b66-9eef-11e7-9315-01f1132e1cd3.png)

**Comment by ocefpaf** [comment]
@FrancoisMB I don't think that `mplleaflet`, or `matplotlib`, should take care of the projection here.

Your alternatives are:

- check cartopy which will probably provide a way to handle `mpl.patches` with projections;
- go straight to leaflet vector layers for simple forms like those.

**Comment by jwass** [comment]
@FrancoisMB I agree with @ocefpaf. By default, mplleaflet doesn't re-project the data. It just places those on a webmap.
