### ISSUE TITLE
Upload to PyPI

### ISSUE THREAD

**Issue by olethanh** [jwass/mplleaflet#8]
Hello,

I really like this project but could you please push it on pypi? it would help installation on our part.
Thanks

**Comment by jackiekazil** [comment]
Hey! I just tried to pip install this. :-) It doesn't have to be perfect to upload to pypi.

**Comment by jwass** [comment]
@jackiekazil Thanks for the nudge :)

mplleaflet is now on PyPI! Thanks.

**Comment by jackiekazil** [comment]
:+1:
